version: "3.4"
services:
  myapp-service:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    container_name: myapp-service
    command:  "sh -c \"cd app && fresh\" "
    volumes:
      - ../..:/go/src/github.com/adirutwn/go-clean
    links:
      - postgres-db
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myapp
      PORT: 8080

  postgres-db:
    image: "postgres:9.5-alpine"
    container_name: postgres-db
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    restart: 'always'
    ports:
      - "5433:5432"

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - 5050:5050